version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - ./data:/app/data
    environment:
      - DB_PATH=/app/data/database.db
      - SKIP_API_KEY=${SKIP_API_KEY}
    restart: unless-stopped 